import {
  GET_DEPARTMENTS_REQUEST,
  GET_DEPARTMENTS_SUCCESS,
  GET_DEPARTMENTS_FAILURE,
  CREATE_DEPARTMENT_REQUEST,
  CREATE_DEPARTMENT_SUCCESS,
  CREATE_DEPARTMENT_FAILURE,
  UPDATE_DEPARTMENT_REQUEST,
  UPDATE_DEPARTMENT_SUCCESS,
  UPDATE_DEPARTMENT_FAILURE,
  DELETE_DEPARTMENT_REQUEST,
  DELETE_DEPARTMENT_SUCCESS,
  DELETE_DEPARTMENT_FAILURE
} from 'constants/action_types/departments'
import Abstract from './abstract'

export default class Department extends Abstract {

  static URL = `${Abstract.API}/departments`

  static ACTION_TYPES = {
    QUERY_REQUEST:  GET_DEPARTMENTS_REQUEST,
    QUERY_SUCCESS:  GET_DEPARTMENTS_SUCCESS,
    QUERY_FAILURE:  GET_DEPARTMENTS_FAILURE,

    CREATE_REQUEST: CREATE_DEPARTMENT_REQUEST,
    CREATE_SUCCESS: CREATE_DEPARTMENT_SUCCESS,
    CREATE_FAILURE: CREATE_DEPARTMENT_FAILURE,
    
    UPDATE_REQUEST: UPDATE_DEPARTMENT_REQUEST,
    UPDATE_SUCCESS: UPDATE_DEPARTMENT_SUCCESS,
    UPDATE_FAILURE: UPDATE_DEPARTMENT_FAILURE,
   
    DELETE_REQUEST: DELETE_DEPARTMENT_REQUEST,
    DELETE_SUCCESS: DELETE_DEPARTMENT_SUCCESS,
    DELETE_FAILURE: DELETE_DEPARTMENT_FAILURE
  }
}
