import {
  GET_DEVELOPERS_REQUEST,
  GET_DEVELOPERS_SUCCESS,
  GET_DEVELOPERS_FAILURE,
  CREATE_DEVELOPER_REQUEST,
  CREATE_DEVELOPER_SUCCESS,
  CREATE_DEVELOPER_FAILURE,
  UPDATE_DEVELOPER_REQUEST,
  UPDATE_DEVELOPER_SUCCESS,
  UPDATE_DEVELOPER_FAILURE,
  DELETE_DEVELOPER_REQUEST,
  DELETE_DEVELOPER_SUCCESS,
  DELETE_DEVELOPER_FAILURE
} from 'constants/action_types/developers'
import Abstract from './abstract'

export default class Developer extends Abstract {

  static URL = `${Abstract.API}/developers`

  static ACTION_TYPES = {
    QUERY_REQUEST:  GET_DEVELOPERS_REQUEST,
    QUERY_SUCCESS:  GET_DEVELOPERS_SUCCESS,
    QUERY_FAILURE:  GET_DEVELOPERS_FAILURE,

    CREATE_REQUEST: CREATE_DEVELOPER_REQUEST,
    CREATE_SUCCESS: CREATE_DEVELOPER_SUCCESS,
    CREATE_FAILURE: CREATE_DEVELOPER_FAILURE,
    
    UPDATE_REQUEST: UPDATE_DEVELOPER_REQUEST,
    UPDATE_SUCCESS: UPDATE_DEVELOPER_SUCCESS,
    UPDATE_FAILURE: UPDATE_DEVELOPER_FAILURE,
   
    DELETE_REQUEST: DELETE_DEVELOPER_REQUEST,
    DELETE_SUCCESS: DELETE_DEVELOPER_SUCCESS,
    DELETE_FAILURE: DELETE_DEVELOPER_FAILURE
  }
  serialize() {
    this.departmentId = this.department.id
    return this 
  }
}
