import {
  GET_SPRINTS_REQUEST,
  GET_SPRINTS_SUCCESS,
  GET_SPRINTS_FAILURE,
 
  GET_SPRINT_REQUEST,
  GET_SPRINT_SUCCESS,
  GET_SPRINT_FAILURE,

  CREATE_SPRINT_REQUEST,
  CREATE_SPRINT_SUCCESS,
  CREATE_SPRINT_FAILURE,
 
  UPDATE_SPRINT_REQUEST,
  UPDATE_SPRINT_SUCCESS,
  UPDATE_SPRINT_FAILURE,
  
  DELETE_SPRINT_REQUEST,
  DELETE_SPRINT_SUCCESS,
  DELETE_SPRINT_FAILURE
} from 'constants/action_types/sprints'
import Abstract from './abstract'

export default class Sprint extends Abstract {

  static URL = `${Abstract.API}/sprints`

  static ACTION_TYPES = {
    QUERY_REQUEST:  GET_SPRINTS_REQUEST,
    QUERY_SUCCESS:  GET_SPRINTS_SUCCESS,
    QUERY_FAILURE:  GET_SPRINTS_FAILURE,

    GET_REQUEST: GET_SPRINT_REQUEST,
    GET_SUCCESS: GET_SPRINT_SUCCESS,
    GET_FAILURE: GET_SPRINT_FAILURE,
    
    CREATE_REQUEST: CREATE_SPRINT_REQUEST,
    CREATE_SUCCESS: CREATE_SPRINT_SUCCESS,
    CREATE_FAILURE: CREATE_SPRINT_FAILURE,
    
    UPDATE_REQUEST: UPDATE_SPRINT_REQUEST,
    UPDATE_SUCCESS: UPDATE_SPRINT_SUCCESS,
    UPDATE_FAILURE: UPDATE_SPRINT_FAILURE,
   
    DELETE_REQUEST: DELETE_SPRINT_REQUEST,
    DELETE_SUCCESS: DELETE_SPRINT_SUCCESS,
    DELETE_FAILURE: DELETE_SPRINT_FAILURE
  }

  serialize() {
    return this
  }
}
