version: '2'
services:
  db:
    image: postgres
  back:
    container_name: back
    tty: true
    stdin_open: true
    build:
      context: backend
      dockerfile: Dockerfile
    command:  bash -c "cd backend && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  front:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: bash -c "cd frontend && npm start"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - back
