source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.1'
gem 'dry-system-rails'
gem 'jsonapi-serializers'

gem 'jira-ruby', :require => 'jira-ruby'

gem 'rademade_admin', github: 'Rademade/rademade_admin', branch: 'feature/rails-5'
gem 'pg'

group :development, :test do
  gem 'awesome_rails_console'
  gem 'hirb'
  gem 'annotate', git: 'https://github.com/ctran/annotate_models.git'
end

group :development do
  gem 'web-console', '~> 2.0'
end
