export const GET_DASHBOARD_DEVELOPERS_REQUEST = 'GET_DASHBOARD_DEVELOPERS_REQUEST';
export const GET_DASHBOARD_DEVELOPERS_SUCCESS = 'GET_DASHBOARD_DEVELOPERS_SUCCESS';
export const GET_DASHBOARD_DEVELOPERS_FAILURE = 'GET_DASHBOARD_DEVELOPERS_FAILURE';
export const GET_DASHBOARD_REQUEST = 'GET_DASHBOARD_REQUEST';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAILURE = 'GET_DASHBOARD_FAILURE';
