export const GET_DEVELOPERS_REQUEST = 'GET_DEVELOPERS_REQUEST';
export const GET_DEVELOPERS_SUCCESS = 'GET_DEVELOPERS_SUCCESS';
export const GET_DEVELOPERS_FAILURE = 'GET_DEVELOPERS_FAILURE';

export const CREATE_DEVELOPER_REQUEST = 'POST_DEVELOPER_REQUEST'
export const CREATE_DEVELOPER_SUCCESS = 'POST_DEVELOPER_SUCCESS'
export const CREATE_DEVELOPER_FAILURE = 'POST_DEVELOPER_FAILURE'

export const UPDATE_DEVELOPER_REQUEST = 'UPDATE_DEVELOPER_REQUEST'
export const UPDATE_DEVELOPER_SUCCESS = 'UPDATE_DEVELOPER_SUCCESS'
export const UPDATE_DEVELOPER_FAILURE = 'UPDATE_DEVELOPER_FAILURE'

export const DELETE_DEVELOPER_REQUEST = 'DELETE_DEVELOPER_REQUEST'
export const DELETE_DEVELOPER_SUCCESS = 'DELETE_DEVELOPER_SUCCESS'
export const DELETE_DEVELOPER_FAILURE = 'DELETE_DEVELOPER_FAILURE'
