export const GET_SPRINTS_REQUEST = 'GET_SPRINTS_REQUEST';
export const GET_SPRINTS_SUCCESS = 'GET_SPRINTS_SUCCESS';
export const GET_SPRINTS_FAILURE = 'GET_SPRINTS_FAILURE';

export const GET_SPRINT_REQUEST = 'GET_SPRINT_REQUEST';
export const GET_SPRINT_SUCCESS = 'GET_SPRINT_SUCCESS';
export const GET_SPRINT_FAILURE = 'GET_SPRINT_FAILURE';
